
  services:
    zookeeper:
      image: wurstmeister/zookeeper:latest
      container_name: zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: wurstmeister/kafka:latest
      container_name: kafka
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "raw-threat-data:1:1"
      ports:
        - "9092:9092"

    mysql:
      image: mysql:8.0
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: threat_intel
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql

  volumes:
    mysql-data:
